service: farafonoff-aws-cart-service
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  deploymentMethod: direct
  architecture: arm64
functions:
  cart-service:
    handler: dist/mainLambda.handler
    url: true
    environment:
      POSTGRES_HOST: !GetAtt CartDB.Endpoint.Address
      POSTGRES_PORT: !GetAtt CartDB.Endpoint.Port
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '{{resolve:ssm:db_password}}'
      POSTGRES_DATABASE: cart
resources:
  Resources:
    CartDB:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: '20'
        DBInstanceClass: db.t4g.micro
        Engine: postgres
        MasterUsername: postgres
        MasterUserPassword: '{{resolve:ssm:db_password}}'
        PubliclyAccessible: true
        BackupRetentionPeriod: 0
      DeletionPolicy: Snapshot
  Outputs:
    DatabaseHost:
      Value: !GetAtt CartDB.Endpoint.Address
      Export:
        Name: DatabaseHost
    DatabasePort:
      Value: !GetAtt CartDB.Endpoint.Port
      Export:
        Name: DatabasePort
